name: Glog Scan (dev)
on:
  workflow_dispatch:

jobs:
  glog-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Checkout glog-action repository
        uses: actions/checkout@v6
        with:
          repository: glogai/glog-action
          token: ${{ secrets.PAT_TOKEN }}
          path: .github/glog-action
          ref: main

      - name: Run Glog.AI
        uses: ./.github/glog-action
        with:
          client: 'test'
          github-token: ${{ secrets.PAT_TOKEN }}
          glog-token: ${{ secrets.GLOG_TOKEN }}
          upload: 'true'
          on-prem-upload: 'true'
          issue: 'false'
          autofix: 'false'
          sarif-format-type: 'GITHUB'
          server-sarif-format-type: 'STANDARD'
          sbom: 'true'
          supply-chain: 'true'
          rebuild: 'true'
          rebuild-max-packages: '25'
          env: 'dev'
          scl-uuid: 'f542682f-82d4-43e1-b5cd-c9d7800cee73'
